server:
  servlet:
    context-path: /
spring:
  application:
    name: test-spring
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: fortest
    password: 123

rabbitmq:
  queueName: test
  topicExchange:
      name: topic
      routeKey: topic-queue
